name: Android CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v2
    -   name: set up JDK 11
        uses: actions/setup-java@v2
        with:
            distribution: 'adopt' 
            java-version: '11'
    -   name: Grant execute permission for gradlew
        run: chmod +x gradlew
    -   name: Check code style
        run: ./gradlew ktLiCh
    -   name: Run tests
        run: ./gradlew sdk:testDebug --stacktrace
    -   name: Build APK
        run: ./gradlew sdk-sample:assembleDebug --stacktrace
