name: Android CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v2
    -   name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
            java-version: 1.8
    -   name: Grant execute permission for gradlew
        run: chmod +x gradlew
    -   name: Check code style
        run: ./gradlew ktLiCh
    -   name: Run tests
        run: ./gradlew testDebug --stacktrace
    -   name: Build APK
        run: ./gradlew assembleDebug --stacktrace
