name: Build and test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -   uses: actions/checkout@v4
    -   name: set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'corretto'
            java-version: '17'
            cache: 'gradle'
    -   name: Grant execute permission for gradlew
        run: chmod +x gradlew
    -   name: Check code style
        run: ./gradlew ktlintCheck --continue
    -   name: Check API binary compatibility
        run: ./gradlew apiCheck
    -   name: Run tests and build project
        run: ./gradlew sdk:testDebug sdk-sample:assembleDebug --stacktrace
